
@host =  http://localhost:5053
GET {{host}}/dinners

Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWFmOGFhZi1lNWQ2LTQzNGEtYWU4Mi00NTFhNzNhYTI3MzgiLCJnaXZlbl9uYW1lIjoiWGF2aWVyIiwiZmFtaWx5X25hbWUiOiJKb2huIiwianRpIjoiMmMwYmE0NWQtNWUyOS00ZTNkLTk4ZjgtNGNjY2I1OTBjMDI0IiwiZXhwIjoxNzE5NTA5ODExLCJpc3MiOiJCdWJlckRpbmVyIiwiYXVkIjoiQnViZXJEaW5lciJ9.r8PUc3tN56UEUE95FJsukqXaL7Rclh6y6DRmku97NYY